# config.toml

baseURL      = "https://cezarmathe.com/"
languageCode = "en-us"

author = "Armand-Cezar Mathe"
title  = "Cezar's website"

enableRobotsTXT = true

[minify]
minifyOutput = true

[params]
author               = "Armand-Cezar Mathe"
firstPublicationDate = 2019
copyrightUrl         = "/copyright"

[params.avatar]
src = "/hero.jpeg"
alt = "A picture of me."

[[params.external_links]]
name    = "email"
display = "me@cezarmathe.com"
link    = "mailto:me@cezarmathe.com"

[[params.external_links]]
name    = "github"
display = "cezarmathe"
link    = "https://github.com/cezarmathe"

[[params.external_links]]
name    = "linkedin"
display = "Armand Cezar Mathe"
link    = "https://www.linkedin.com/in/cezarmathe/"

[[params.nav]]
url     = "/random"
display = "random stuff"
