# config.toml

baseURL      = "https://cezarmathe.com/"
languageCode = "en-us"

author = "Armand-Cezar Mathe"
title  = "Cezar's website"

enableRobotsTXT = true

[minify]
minifyOutput = true

[params]
author               = "Armand-Cezar Mathe"
avatar               = "/avatar.img"
firstPublicationDate = "2019"

[params.content]
license_url      = "https://creativecommons.org/licenses/by-sa/4.0/"
license_display  = "CC-BY-SA"
license_copy_url = "/content-license.txt"

[params.source]
license_url      = "https://choosealicense.com/licenses/mit/"
license_display  = "MIT"
license_copy_url = "/license.txt"
url              = "https://github.com/cezarmathe/personal-website"

[[params.links]]
name    = "email"
display = "me@cezarmathe.com"
link    = "mailto:me@cezarmathe.com"

[[params.links]]
name    = "github"
display = "cezarmathe"
link    = "https://github.com/cezarmathe"

[[params.links]]
name    = "mastodon"
display = "@tvcx@mastodon.social"
link    = "https://mastodon.social/@tvcx"
rel     = "me"
attrs   = ['rel="me"']

[params.mastofeed]
url = "https://www.mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Fmastodon.social%2F%40tvcx&theme=auto&header=true&replies=false&boosts=false"
